// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApiArchivos.DataBaseArchivos.Models
{
    public partial class SpGetArchivoEspecificoResult
    {
        public Guid IdArchivo { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
        public string MimeType { get; set; }
        public string Ruta { get; set; }
        public DateTime? Fecha { get; set; }
        public int? IdAlmacenamiento { get; set; }
        public string IdAplicacion { get; set; }
        public long? ByteLenght { get; set; }
    }
}
