// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApiArchivos.DataBaseArchivos.Models
{
    public partial class spLoginAlmacenamientoResult
    {
        public int IdAlmacenamiento { get; set; }
        public string Nombre { get; set; }
        public string IP { get; set; }
        public string Servidor { get; set; }
        public int? Puerto { get; set; }
        public string Protocolo { get; set; }
        public string Raiz { get; set; }
        public string RutaFisica { get; set; }
    }
}
