// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApiArchivos.DataBaseArchivos.Models;

namespace WebApiArchivos.DataBaseArchivos.Context
{
    public partial interface IArchivosContextProcedures
    {
        Task<List<SpGetAlmacenamientoResult>> SpGetAlmacenamientoAsync(int? IdAlmacenamiento, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpGetArchivoEspecificoResult>> SpGetArchivoEspecificoAsync(string IdArchivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spLoginAlmacenamientoResult>> spLoginAlmacenamientoAsync(string Keyname, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spRegistrarArchivoAsync(Guid? IdArchivo, string Nombre, string Extension, string MimeType, string Ruta, int? IdAlmacenamiento, int? IdAplicacion, long? ByteLenght, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
